server:
  port: 8081

spring:
  data:
    redis:
      host: "${REDIS_HOST:redis}"
      port: 6379

internal:
  hmac:
    secret: ${INTERNAL_HMAC_SECRET}

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when-authorized
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
