import { appendFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { BrowserContext, Download, Page } from '@playwright/test';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// 2026-08-24 full-stack QA pass (see qa-artifacts/REPORT.md). Attaches
// context-level console/pageerror/requestfailed/http-error/download listeners
// so every anomaly across every route+role is captured to one append-only
// JSONL log, without needing to thread assertions through every single click.
// REPORT.md §1/§2 are generated by reading this file back.

const LOG_DIR = path.resolve(__dirname, '..', '..', '..', '..', 'qa-artifacts');
const LOG_FILE = path.join(LOG_DIR, 'REPORT_LOG.jsonl');
export const DOWNLOAD_DIR = path.join(LOG_DIR, 'downloads');

mkdirSync(LOG_DIR, { recursive: true });
mkdirSync(DOWNLOAD_DIR, { recursive: true });

export interface QaMeta {
  role: string;
  locale?: 'it' | 'en';
}

function write(entry: Record<string, unknown>): void {
  appendFileSync(LOG_FILE, JSON.stringify({ ts: new Date().toISOString(), ...entry }) + '\n', 'utf-8');
}

/** Known-noise allowlist — anything matched here is still logged (allowlisted:reason), never dropped silently. */
const NOISE_ALLOWLIST: Array<{ match: RegExp; reason: string }> = [
  { match: /\[vite\]|\[HMR\]|WebSocket connection.*failed.*vite/i, reason: 'Vite HMR socket — irrelevant against the nginx build' },
];

function noiseReason(text: string): string | null {
  for (const rule of NOISE_ALLOWLIST) if (rule.match.test(text)) return rule.reason;
  return null;
}

let currentRoute = '(unset)';
let currentAction = '(unset)';
export function setContext(route: string, action = ''): void {
  currentRoute = route;
  currentAction = action;
}

export function logCustom(kind: string, data: Record<string, unknown>): void {
  write({ kind, route: currentRoute, action: currentAction, ...data });
}

export function attachQaListeners(context: BrowserContext, meta: QaMeta): void {
  context.on('console', (msg) => {
    const type = msg.type();
    if (type !== 'error' && type !== 'warning') return;
    const text = msg.text();
    write({
      kind: 'console', level: type, text, location: msg.location(),
      route: currentRoute, action: currentAction, ...meta, allowlisted: noiseReason(text),
    });
  });
  context.on('page', (page: Page) => {
    page.on('pageerror', (err) => write({
      kind: 'pageerror', message: err.message, stack: err.stack,
      route: currentRoute, action: currentAction, ...meta,
    }));
    page.on('requestfailed', (req) => write({
      kind: 'requestfailed', url: req.url(), method: req.method(),
      failure: req.failure()?.errorText, route: currentRoute, action: currentAction, ...meta,
    }));
    page.on('response', (res) => {
      const status = res.status();
      if (status < 400) return;
      write({
        kind: 'http_error', url: res.url(), status, method: res.request().method(),
        route: currentRoute, action: currentAction, ...meta,
      });
    });
  });
  context.on('download', (dl: Download) => write({
    kind: 'download', suggestedFilename: dl.suggestedFilename(), url: dl.url(),
    route: currentRoute, action: currentAction, ...meta,
  }));
}
